"""Synthetic infrasound signal generator for demo mode.

All signals generated here are SYNTHETIC and intended for demonstration
purposes only. They approximate the general characteristics of real
infrasound phenomena but are NOT scientifically validated recordings.

Typical infrasound frequencies: 0.001 Hz to 20 Hz.
"""

import logging
import uuid
from datetime import datetime
from typing import Optional

import numpy as np
from numpy.typing import NDArray

from .models import EventType, InjectedEvent, SignalChunk

logger = logging.getLogger(__name__)

# Type alias for clarity
Signal = NDArray[np.float64]


class InfrasoundGenerator:
    """Generates synthetic infrasound signals for demo/testing.

    This generator produces realistic-looking low-frequency waveforms
    that mimic atmospheric infrasound patterns. The generated signals
    include background noise, microbarom-like oscillations, and
    injectable transient events.

    All outputs are synthetic demonstrations.
    """

    def __init__(
        self,
        sample_rate: float = 100.0,
        seed: Optional[int] = None,
    ) -> None:
        self.sample_rate = sample_rate
        self.rng = np.random.default_rng(seed)
        self._phase_offset: float = 0.0
        self._time_counter: float = 0.0
        self._pending_event: Optional[EventType] = None
        self._pending_event_remaining: int = 0
        self._current_event_type: EventType = EventType.BACKGROUND
        self._injected_events: list[InjectedEvent] = []

    def generate_background(self, n_samples: int) -> Signal:
        """Generate atmospheric background noise.

        Combines pink-ish noise with very low frequency drift to
        simulate ambient atmospheric pressure variations.

        Args:
            n_samples: Number of samples to generate.

        Returns:
            Background noise signal array.
        """
        # Pink-ish noise (1/f spectrum approximation)
        white = self.rng.standard_normal(n_samples)
        # Simple 1/f approximation via cumulative filtering
        pink = np.zeros(n_samples)
        b = [0.049922035, -0.095993537, 0.050612699, -0.004709510]
        a_state = [0.0, 0.0, 0.0, 0.0]
        for i in range(n_samples):
            a_state[0] = 0.99886 * a_state[0] + white[i] * 0.0555179
            a_state[1] = 0.99332 * a_state[1] + white[i] * 0.0750759
            a_state[2] = 0.96900 * a_state[2] + white[i] * 0.1538520
            a_state[3] = 0.86650 * a_state[3] + white[i] * 0.3104856
            pink[i] = (
                a_state[0] + a_state[1] + a_state[2] + a_state[3]
                + white[i] * 0.5362
            )
        pink *= 0.05  # Scale down

        # Very low frequency drift (< 0.01 Hz)
        t = np.arange(n_samples) / self.sample_rate + self._time_counter
        drift = 0.02 * np.sin(2 * np.pi * 0.003 * t + self._phase_offset)
        drift += 0.01 * np.sin(2 * np.pi * 0.007 * t + self._phase_offset * 1.3)

        return pink + drift

    def generate_microbarom_like(self, n_samples: int) -> Signal:
        """Generate microbarom-like oscillations (synthetic).

        Microbaroms are infrasound signals generated by ocean waves.
        This synthetic version uses dual-frequency beating patterns
        in the 0.1-0.5 Hz range.

        Args:
            n_samples: Number of samples to generate.

        Returns:
            Microbarom-like signal array.
        """
        t = np.arange(n_samples) / self.sample_rate + self._time_counter

        # Primary microbarom frequencies (0.15 - 0.3 Hz typically)
        f1 = 0.18 + 0.02 * np.sin(2 * np.pi * 0.001 * t)
        f2 = 0.22 + 0.015 * np.sin(2 * np.pi * 0.0015 * t)

        signal = 0.3 * np.sin(2 * np.pi * np.cumsum(f1) / self.sample_rate)
        signal += 0.25 * np.sin(2 * np.pi * np.cumsum(f2) / self.sample_rate)

        # Amplitude modulation
        envelope = 0.8 + 0.2 * np.sin(2 * np.pi * 0.005 * t)
        signal *= envelope

        return signal

    def generate_explosion_like(self, n_samples: int) -> Signal:
        """Generate explosion-like transient signal (synthetic).

        Simulates a sharp onset followed by exponential decay with
        broadband frequency content, similar to what an explosion
        might produce in the infrasound band.

        Args:
            n_samples: Number of samples to generate.

        Returns:
            Explosion-like signal array.
        """
        t = np.arange(n_samples) / self.sample_rate

        # Sharp onset with exponential decay
        duration = n_samples / self.sample_rate
        tau = duration * 0.15  # Decay time constant
        onset_idx = int(0.1 * n_samples)

        envelope = np.zeros(n_samples)
        decay_len = n_samples - onset_idx
        if decay_len > 0:
            decay_t = np.arange(decay_len) / self.sample_rate
            envelope[onset_idx:] = np.exp(-decay_t / tau)

        # Broadband content
        signal = np.zeros(n_samples)
        for freq in [0.5, 1.0, 2.0, 3.5, 5.0, 8.0]:
            amp = 1.0 / (1.0 + freq * 0.3)
            phase = self.rng.uniform(0, 2 * np.pi)
            signal += amp * np.sin(2 * np.pi * freq * t + phase)

        signal *= envelope * 1.5

        # Add some impulsive content at onset
        if onset_idx < n_samples:
            impulse_len = min(50, n_samples - onset_idx)
            signal[onset_idx : onset_idx + impulse_len] += (
                self.rng.standard_normal(impulse_len) * 0.8
            )

        return signal

    def generate_meteor_like(self, n_samples: int) -> Signal:
        """Generate meteor-like infrasound signal (synthetic).

        Simulates the acoustic signature of a bolide/meteor entry,
        with a gradual buildup, sharp peak, and extended decay with
        frequency glide.

        Args:
            n_samples: Number of samples to generate.

        Returns:
            Meteor-like signal array.
        """
        t = np.arange(n_samples) / self.sample_rate
        duration = n_samples / self.sample_rate

        # Envelope: ramp up then exponential decay
        peak_pos = 0.3
        peak_idx = int(peak_pos * n_samples)
        envelope = np.zeros(n_samples)

        # Ramp up
        if peak_idx > 0:
            envelope[:peak_idx] = np.linspace(0, 1, peak_idx) ** 2

        # Decay
        decay_len = n_samples - peak_idx
        if decay_len > 0:
            decay_t = np.arange(decay_len) / self.sample_rate
            tau = duration * 0.25
            envelope[peak_idx:] = np.exp(-decay_t / tau)

        # Frequency glide (descending)
        f_start = 5.0
        f_end = 0.8
        freq = np.linspace(f_start, f_end, n_samples)
        phase = 2 * np.pi * np.cumsum(freq) / self.sample_rate

        signal = np.sin(phase) * envelope * 1.2

        # Add harmonics
        signal += 0.3 * np.sin(2.1 * phase) * envelope
        signal += 0.15 * np.sin(3.3 * phase) * envelope

        # Scatter some noise
        signal += self.rng.standard_normal(n_samples) * 0.1 * envelope

        return signal

    def generate_volcanic_like(self, n_samples: int) -> Signal:
        """Generate volcanic tremor-like infrasound signal (synthetic).

        Simulates volcanic infrasound with sustained low-frequency
        tremor, harmonic content, and amplitude fluctuations.

        Args:
            n_samples: Number of samples to generate.

        Returns:
            Volcanic-like signal array.
        """
        t = np.arange(n_samples) / self.sample_rate

        # Sustained fundamental (0.5-2 Hz range for volcanic)
        f0 = 1.2 + 0.3 * np.sin(2 * np.pi * 0.02 * t)
        phase0 = 2 * np.pi * np.cumsum(f0) / self.sample_rate

        signal = 0.8 * np.sin(phase0)
        signal += 0.4 * np.sin(2 * phase0)  # 1st harmonic
        signal += 0.2 * np.sin(3 * phase0)  # 2nd harmonic

        # Amplitude modulation (tremor pulsation)
        tremor_mod = 0.6 + 0.4 * np.sin(2 * np.pi * 0.08 * t)
        signal *= tremor_mod

        # Envelope: gradual onset and sustained
        envelope = np.ones(n_samples)
        ramp = min(int(0.15 * n_samples), n_samples)
        envelope[:ramp] = np.linspace(0.1, 1.0, ramp)
        decay_start = int(0.8 * n_samples)
        decay_len = n_samples - decay_start
        if decay_len > 0:
            envelope[decay_start:] = np.linspace(1.0, 0.3, decay_len)

        signal *= envelope

        # Add volcanic noise
        signal += self.rng.standard_normal(n_samples) * 0.15

        return signal

    def generate_random_anomaly(self, n_samples: int) -> Signal:
        """Generate a random anomalous signal pattern (synthetic).

        Creates an unusual signal that doesn't fit typical categories,
        combining multiple unusual features.

        Args:
            n_samples: Number of samples to generate.

        Returns:
            Random anomaly signal array.
        """
        t = np.arange(n_samples) / self.sample_rate

        # Random combination of unusual features
        signal = np.zeros(n_samples)

        # Chirp signal
        f0 = self.rng.uniform(0.5, 3.0)
        f1 = self.rng.uniform(5.0, 15.0)
        freq_sweep = np.linspace(f0, f1, n_samples)
        chirp = np.sin(2 * np.pi * np.cumsum(freq_sweep) / self.sample_rate)
        signal += chirp * 0.6

        # Burst noise
        n_bursts = self.rng.integers(2, 6)
        for _ in range(n_bursts):
            burst_center = self.rng.integers(0, n_samples)
            burst_width = self.rng.integers(20, 100)
            burst_start = max(0, burst_center - burst_width // 2)
            burst_end = min(n_samples, burst_center + burst_width // 2)
            signal[burst_start:burst_end] += (
                self.rng.standard_normal(burst_end - burst_start) * 0.8
            )

        # Amplitude envelope
        envelope = np.ones(n_samples)
        ramp = min(int(0.1 * n_samples), n_samples)
        envelope[:ramp] = np.linspace(0, 1, ramp)
        envelope[-ramp:] = np.linspace(1, 0, ramp)
        signal *= envelope

        return signal

    def inject_event(self, event_type: EventType) -> InjectedEvent:
        """Schedule an event injection into the next generated chunk.

        Args:
            event_type: Type of event to inject.

        Returns:
            InjectedEvent descriptor.
        """
        event = InjectedEvent(
            event_id=str(uuid.uuid4()),
            event_type=event_type,
            station_id="INFRA-001",
            timestamp=datetime.utcnow().isoformat() + "Z",
            duration_seconds=5.0,
        )
        self._pending_event = event_type
        self._pending_event_remaining = int(5.0 * self.sample_rate)
        self._injected_events.append(event)
        logger.info(
            "Scheduled event injection: %s (id=%s)",
            event_type.value,
            event.event_id,
        )
        return event

    def generate_chunk(
        self,
        n_samples: int = 256,
        station_id: str = "INFRA-001",
    ) -> SignalChunk:
        """Generate a chunk of signal data.

        If an event has been injected, the chunk will contain
        the event signal mixed with background. Otherwise,
        it produces normal background + microbarom-like patterns.

        Args:
            n_samples: Number of samples per chunk.
            station_id: Station identifier.

        Returns:
            SignalChunk with generated data.
        """
        background = self.generate_background(n_samples)
        microbarom = self.generate_microbarom_like(n_samples)
        signal = background + microbarom * 0.3

        event_type = EventType.BACKGROUND

        if self._pending_event is not None and self._pending_event_remaining > 0:
            event_type = self._pending_event
            chunk_event_samples = min(n_samples, self._pending_event_remaining)

            event_signal: Signal
            if self._pending_event == EventType.EXPLOSION_LIKE:
                event_signal = self.generate_explosion_like(chunk_event_samples)
            elif self._pending_event == EventType.METEOR_LIKE:
                event_signal = self.generate_meteor_like(chunk_event_samples)
            elif self._pending_event == EventType.VOLCANIC_LIKE:
                event_signal = self.generate_volcanic_like(chunk_event_samples)
            elif self._pending_event == EventType.RANDOM_ANOMALY:
                event_signal = self.generate_random_anomaly(chunk_event_samples)
            else:
                event_signal = self.generate_microbarom_like(chunk_event_samples) * 2.0

            signal[:chunk_event_samples] += event_signal

            self._pending_event_remaining -= chunk_event_samples
            if self._pending_event_remaining <= 0:
                self._pending_event = None
                self._pending_event_remaining = 0

        self._time_counter += n_samples / self.sample_rate

        return SignalChunk.from_numpy(
            station_id=station_id,
            samples=signal,
            sample_rate=self.sample_rate,
            event_type=event_type,
        )

    def stream_samples(
        self,
        chunk_size: int = 256,
        station_id: str = "INFRA-001",
    ):
        """Yield an infinite stream of signal chunks.

        Args:
            chunk_size: Samples per chunk.
            station_id: Station identifier.

        Yields:
            SignalChunk objects continuously.
        """
        while True:
            yield self.generate_chunk(
                n_samples=chunk_size,
                station_id=station_id,
            )

    @property
    def last_injected_event(self) -> Optional[InjectedEvent]:
        """Get the most recently injected event."""
        if self._injected_events:
            return self._injected_events[-1]
        return None

    @property
    def has_pending_event(self) -> bool:
        """Check if there's an active event injection."""
        return self._pending_event is not None and self._pending_event_remaining > 0
